import { spawn } from 'node:child_process'
import { randomBytes, timingSafeEqual } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { type IncomingMessage, type Server, type ServerResponse, createServer } from 'node:http'
import type { AddressInfo } from 'node:net'
import { resolve } from 'node:path'
import { type Receipt, verifyReceipts } from 'nominee'
import { CONSOLE_CSS, CONSOLE_HTML, CONSOLE_JS } from './console-assets.js'
import { generateStarterPolicy, parseObservationReport } from './policy.js'

const BODY_LIMIT = 256 * 1024
const MAX_RECEIPTS = 1_000
const MAX_ACTIVITY = 100
const MAX_APPROVAL_WAIT_MS = 10 * 60_000
const COOKIE = 'nominee_console'

type ParsedReport = ReturnType<typeof parseObservationReport>
type ApprovalDecision = 'approved' | 'denied' | 'expired'

interface ReportState {
  report: ParsedReport
  updatedAt: number
  signature: string
}

interface ReceiptChain {
  stream: string
  receipts: Receipt[]
}

interface PendingApproval {
  id: string
  user: string
  action: string
  detail?: unknown
  expiresAt: number
  response: ServerResponse
  timer: ReturnType<typeof setTimeout>
}

interface ActivityEvent {
  at: number
  label: string
  detail: string
}

export interface ConsoleServerOptions {
  /** Loopback interface. Defaults to 127.0.0.1; non-loopback binds are refused. */
  host?: '127.0.0.1' | 'localhost' | '::1'
  /** Port. Defaults to 4317; use 0 in tests for an ephemeral port. */
  port?: number
  /** Producer bearer token. A random 256-bit token is generated by default. */
  token?: string
  /** HMAC key used only to verify live receipts. Defaults to NOMINEE_RECEIPT_KEY. */
  receiptKey?: string
  /** Fixed local policy destination used by the UI. Defaults to ./nominee.policy.ts. */
  policyOut?: string
  /** Optional preloaded observe report. */
  initialReport?: unknown
  /** Optional preloaded receipt chain. */
  initialReceipts?: Receipt[]
  /** Open the authenticated bootstrap URL in the default browser. Defaults to true. */
  open?: boolean
}

export interface ConsoleServerHandle {
  readonly origin: string
  readonly bootstrapUrl: string
  readonly token: string
  readonly closed: Promise<void>
  close(): Promise<void>
}

export interface RunConsoleOptions {
  reportFile?: string
  receiptsFile?: string
  policyOut?: string
  port?: number
  open?: boolean
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function secureEqual(actual: string, expected: string): boolean {
  const left = Buffer.from(actual)
  const right = Buffer.from(expected)
  return left.length === right.length && timingSafeEqual(left, right)
}

function securityHeaders(contentType?: string): Record<string, string> {
  return {
    ...(contentType ? { 'content-type': contentType } : {}),
    'cache-control': 'no-store, max-age=0',
    'content-security-policy':
      "default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
    'cross-origin-opener-policy': 'same-origin',
    'cross-origin-resource-policy': 'same-origin',
    'referrer-policy': 'no-referrer',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY',
  }
}

function send(
  response: ServerResponse,
  status: number,
  body: string,
  contentType = 'text/plain; charset=utf-8',
  headers: Record<string, string> = {},
): void {
  if (response.writableEnded || response.destroyed) return
  response.writeHead(status, { ...securityHeaders(contentType), ...headers })
  response.end(body)
}

function sendJson(response: ServerResponse, status: number, value: unknown): void {
  send(response, status, JSON.stringify(value), 'application/json; charset=utf-8')
}

async function readJson(request: IncomingMessage): Promise<unknown> {
  if (!request.headers['content-type']?.toLowerCase().startsWith('application/json')) {
    throw Object.assign(new Error('content-type must be application/json'), { status: 415 })
  }
  const chunks: Buffer[] = []
  let size = 0
  let tooLarge = false
  for await (const chunk of request) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)
    size += buffer.length
    if (size > BODY_LIMIT) {
      tooLarge = true
      continue
    }
    chunks.push(buffer)
  }
  if (tooLarge) throw Object.assign(new Error('request body is too large'), { status: 413 })
  try {
    return JSON.parse(Buffer.concat(chunks).toString('utf8'))
  } catch {
    throw Object.assign(new Error('request body is not valid JSON'), { status: 400 })
  }
}

function parseCookies(header: string | undefined): Map<string, string> {
  const values = new Map<string, string>()
  for (const pair of header?.split(';') ?? []) {
    const separator = pair.indexOf('=')
    if (separator === -1) continue
    values.set(pair.slice(0, separator).trim(), pair.slice(separator + 1).trim())
  }
  return values
}

function validReceipt(value: unknown): value is Receipt {
  return (
    isRecord(value) &&
    Number.isInteger(value.seq) &&
    (value.seq as number) >= 0 &&
    typeof value.at === 'number' &&
    Number.isFinite(value.at) &&
    typeof value.type === 'string' &&
    value.type.length > 0 &&
    value.type.length <= 256 &&
    typeof value.user === 'string' &&
    typeof value.prev === 'string' &&
    typeof value.hash === 'string' &&
    /^[0-9a-f]{64}$/i.test(value.hash) &&
    (value.prev === 'genesis' || /^[0-9a-f]{64}$/i.test(value.prev))
  )
}

function safeStream(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0 && value.length <= 128
}

function reportSignature(report: ParsedReport): string {
  return JSON.stringify([
    report.window.from,
    report.window.to,
    report.totals.calls,
    report.totals.allow,
    report.totals.ask,
    report.totals.deny,
    report.tools.length,
  ])
}

function openBrowser(url: string): void {
  try {
    const command =
      process.platform === 'darwin'
        ? { file: 'open', args: [url] }
        : process.platform === 'win32'
          ? { file: 'cmd', args: ['/c', 'start', '', url] }
          : { file: 'xdg-open', args: [url] }
    const child = spawn(command.file, command.args, { detached: true, stdio: 'ignore' })
    child.once('error', () => {
      // The authenticated URL is printed even when the platform opener is unavailable.
    })
    child.unref()
  } catch {
    // The authenticated URL is always printed, so browser launch is convenience only.
  }
}

/** Start the authenticated, loopback-only console without blocking the caller. */
export async function startConsole(
  options: ConsoleServerOptions = {},
): Promise<ConsoleServerHandle> {
  const host = options.host ?? '127.0.0.1'
  if (!['127.0.0.1', 'localhost', '::1'].includes(host)) {
    throw new Error('nominee console refuses non-loopback bind addresses')
  }
  const requestedPort = options.port ?? 4317
  if (!Number.isInteger(requestedPort) || requestedPort < 0 || requestedPort > 65_535) {
    throw new Error('nominee console port must be an integer from 0 through 65535')
  }
  const producerToken = options.token ?? randomBytes(32).toString('hex')
  if (producerToken.length < 32)
    throw new Error('nominee console token must be at least 32 characters')
  const bootstrapToken = randomBytes(32).toString('hex')
  const uiSession = randomBytes(32).toString('hex')
  const csrf = randomBytes(32).toString('hex')
  const receiptKey = options.receiptKey ?? process.env.NOMINEE_RECEIPT_KEY
  const policyOut = resolve(process.cwd(), options.policyOut ?? 'nominee.policy.ts')

  const reports = new Map<string, ReportState>()
  const chains = new Map<string, ReceiptChain>()
  const pending = new Map<string, PendingApproval>()
  const settled = new Map<string, ApprovalDecision>()
  const activity: ActivityEvent[] = []
  const eventStreams = new Set<ServerResponse>()
  let actualPort = requestedPort
  let closing = false
  let bootstrapAvailable = true

  function addActivity(label: string, detail = ''): void {
    activity.push({ at: Date.now(), label, detail })
    if (activity.length > MAX_ACTIVITY) activity.splice(0, activity.length - MAX_ACTIVITY)
  }

  function latestReport(): ParsedReport | undefined {
    return [...reports.values()].sort((a, b) => b.updatedAt - a.updatedAt)[0]?.report
  }

  function verifyChain(chain: ReceiptChain): {
    kind: 'valid-hmac' | 'valid-unsigned' | 'segment-valid' | 'key-required' | 'invalid'
    label: string
    detail: string
  } {
    const first = chain.receipts[0]
    if (!first) {
      return { kind: 'invalid', label: 'empty', detail: 'No receipts supplied.' }
    }
    const segment = first.seq > 0
    const result = verifyReceipts(chain.receipts, {
      ...(receiptKey ? { key: receiptKey } : {}),
      ...(segment ? { resume: { seq: first.seq, prev: first.prev } } : {}),
    })
    if (result.ok && segment) {
      return {
        kind: 'segment-valid',
        label: 'segment valid',
        detail:
          'This retained segment is internally consistent from its supplied checkpoint; the omitted prefix and overall completeness were not verified.',
      }
    }
    if (result.ok && receiptKey) {
      return {
        kind: 'valid-hmac',
        label: 'HMAC valid',
        detail: `${result.checked} receipts verify from genesis with the configured key. Completeness still requires an external checkpoint.`,
      }
    }
    if (result.ok) {
      return {
        kind: 'valid-unsigned',
        label: 'hash chain valid',
        detail: `${result.checked} receipts verify from genesis. This unsigned chain is tamper-evident but recomputable.`,
      }
    }
    if (!receiptKey) {
      return {
        kind: 'key-required',
        label: 'not verified',
        detail: `Unsigned verification failed at #${result.brokenAt}. The chain may be HMAC-signed (set NOMINEE_RECEIPT_KEY) or may be damaged: ${result.reason}.`,
      }
    }
    return {
      kind: 'invalid',
      label: 'verification failed',
      detail: `The chain failed at #${result.brokenAt}: ${result.reason}.`,
    }
  }

  function publicState(): unknown {
    const report = latestReport()
    const calls = report?.totals.calls ?? 0
    const mutatingCalls =
      report?.tools
        .filter((tool) => tool.kind === 'mutate')
        .reduce((sum, tool) => sum + tool.calls, 0) ?? 0
    const unboundedTools =
      report?.tools.filter((tool) => tool.unboundedArguments.length > 0).length ?? 0
    const toolDetailsIncomplete = Boolean(report?.untrackedTools || report?.toolsTruncated)
    return {
      csrf,
      headlines: {
        calls,
        mutatingCalls,
        unboundedTools,
        toolCount: report?.totals.tools ?? 0,
        toolCountLowerBound: Boolean(report?.toolsTruncated),
        toolDetailsIncomplete,
        denies: report?.policyConfigured
          ? {
              value: report.totals.deny,
              note: 'configured-policy verdicts; none enforced in observe mode',
            }
          : { value: null, note: 'not measured — no policy was configured' },
      },
      canGeneratePolicy: Boolean(
        report && (report.tools.length > 0 || (report.availableTools?.length ?? 0) > 0),
      ),
      tools: report?.tools ?? [],
      approvals: [...pending.values()].map((approval) => ({
        id: approval.id,
        user: approval.user,
        action: approval.action,
        detail: approval.detail,
        expiresAt: approval.expiresAt,
      })),
      activity,
      chains: [...chains.values()].map((chain) => ({
        stream: chain.stream,
        verification: verifyChain(chain),
        receipts: chain.receipts.map((receipt) => ({
          seq: receipt.seq,
          at: receipt.at,
          type: receipt.type,
          tool: receipt.tool,
          effect: receipt.effect,
          decision: receipt.decision,
          outcome: receipt.outcome,
          hash: receipt.hash.slice(0, 12),
        })),
      })),
    }
  }

  function broadcast(): void {
    const payload = `event: state\ndata: ${JSON.stringify(publicState())}\n\n`
    for (const response of eventStreams) {
      if (!response.writableEnded && !response.destroyed) response.write(payload)
    }
  }

  function producerAuthorized(request: IncomingMessage): boolean {
    const header = request.headers.authorization
    return Boolean(header?.startsWith('Bearer ') && secureEqual(header.slice(7), producerToken))
  }

  function uiAuthorized(request: IncomingMessage): boolean {
    const session = parseCookies(request.headers.cookie).get(COOKIE)
    return Boolean(session && secureEqual(session, uiSession))
  }

  function hostAllowed(request: IncomingMessage): boolean {
    const header = request.headers.host?.toLowerCase()
    if (!header) return false
    const hosts = new Set([
      `127.0.0.1:${actualPort}`,
      `localhost:${actualPort}`,
      `[::1]:${actualPort}`,
    ])
    return hosts.has(header)
  }

  function uiMutationAuthorized(request: IncomingMessage): boolean {
    if (!uiAuthorized(request)) return false
    const hostHeader = request.headers.host?.toLowerCase()
    return Boolean(
      request.headers.origin === `http://${hostHeader}` &&
        typeof request.headers['x-nominee-csrf'] === 'string' &&
        secureEqual(request.headers['x-nominee-csrf'], csrf),
    )
  }

  function addReceipt(stream: string, receipt: Receipt): 'added' | 'duplicate' {
    let chain = chains.get(stream)
    if (!chain) {
      chain = { stream, receipts: [] }
      chains.set(stream, chain)
    }
    const last = chain.receipts.at(-1)
    if (last && receipt.seq === last.seq && receipt.hash === last.hash) return 'duplicate'
    if (last && (receipt.seq !== last.seq + 1 || receipt.prev !== last.hash)) {
      throw Object.assign(new Error('receipt is not the next link in this stream'), { status: 409 })
    }
    chain.receipts.push(receipt)
    if (chain.receipts.length > MAX_RECEIPTS) chain.receipts.shift()
    return 'added'
  }

  function settleApproval(id: string, decision: ApprovalDecision): boolean {
    const approval = pending.get(id)
    if (!approval) return false
    pending.delete(id)
    clearTimeout(approval.timer)
    settled.set(id, decision)
    if (settled.size > 500) settled.delete(settled.keys().next().value ?? '')
    sendJson(approval.response, 200, { id, decision })
    addActivity(`Approval ${decision}`, approval.action)
    broadcast()
    return true
  }

  if (options.initialReport !== undefined) {
    const report = parseObservationReport(options.initialReport)
    reports.set('loaded-report', {
      report,
      updatedAt: Date.now(),
      signature: reportSignature(report),
    })
    addActivity('Observation report loaded', `${report.totals.calls} calls`)
  }
  if (options.initialReceipts) {
    for (const receipt of options.initialReceipts) {
      if (!validReceipt(receipt))
        throw new Error('initial receipt file contains an invalid receipt')
      addReceipt('loaded-receipts', receipt)
    }
    if (options.initialReceipts.length) {
      addActivity('Receipt chain loaded', `${options.initialReceipts.length} receipts`)
    }
  }

  const server: Server = createServer((request, response) => {
    void route(request, response).catch((error: unknown) => {
      const status =
        isRecord(error) && typeof error.status === 'number' ? (error.status as number) : 500
      const message = error instanceof Error ? error.message : 'internal error'
      sendJson(response, status, { error: status === 500 ? 'internal error' : message })
    })
  })

  async function route(request: IncomingMessage, response: ServerResponse): Promise<void> {
    if (!hostAllowed(request)) {
      sendJson(response, 421, { error: 'unrecognized Host header' })
      return
    }
    const url = new URL(request.url ?? '/', `http://${request.headers.host}`)
    const method = request.method ?? 'GET'

    if (method === 'GET' && url.pathname === '/bootstrap') {
      const token = url.searchParams.get('token') ?? ''
      if (!bootstrapAvailable || !secureEqual(token, bootstrapToken)) {
        sendJson(response, 401, { error: 'invalid bootstrap token' })
        return
      }
      bootstrapAvailable = false
      send(response, 302, '', 'text/plain; charset=utf-8', {
        location: '/',
        'set-cookie': `${COOKIE}=${uiSession}; HttpOnly; SameSite=Strict; Path=/`,
      })
      return
    }

    if (method === 'GET' && url.pathname === '/app.css') {
      send(response, 200, CONSOLE_CSS, 'text/css; charset=utf-8')
      return
    }
    if (method === 'GET' && url.pathname === '/app.js') {
      send(response, 200, CONSOLE_JS, 'text/javascript; charset=utf-8')
      return
    }
    if (method === 'GET' && url.pathname === '/') {
      if (!uiAuthorized(request)) {
        send(
          response,
          401,
          'nominee console is locked. Open the authenticated URL printed in the terminal.',
        )
        return
      }
      send(response, 200, CONSOLE_HTML, 'text/html; charset=utf-8')
      return
    }
    if (method === 'GET' && url.pathname === '/api/state') {
      if (!uiAuthorized(request)) {
        sendJson(response, 401, { error: 'console session required' })
        return
      }
      sendJson(response, 200, publicState())
      return
    }
    if (method === 'GET' && url.pathname === '/api/events') {
      if (!uiAuthorized(request)) {
        sendJson(response, 401, { error: 'console session required' })
        return
      }
      response.writeHead(200, {
        ...securityHeaders('text/event-stream; charset=utf-8'),
        connection: 'keep-alive',
      })
      response.write(`event: state\ndata: ${JSON.stringify(publicState())}\n\n`)
      eventStreams.add(response)
      response.on('close', () => eventStreams.delete(response))
      return
    }

    if (method === 'POST' && url.pathname === '/api/observations') {
      if (!producerAuthorized(request)) {
        sendJson(response, 401, { error: 'producer bearer token required' })
        return
      }
      const body = await readJson(request)
      if (!isRecord(body) || !safeStream(body.stream)) {
        throw Object.assign(new Error('stream is required'), { status: 400 })
      }
      const report = parseObservationReport(body.report)
      const signature = reportSignature(report)
      const previous = reports.get(body.stream)
      reports.set(body.stream, { report, updatedAt: Date.now(), signature })
      if (previous?.signature !== signature) {
        addActivity('Observation snapshot updated', `${report.totals.calls} calls`)
      }
      sendJson(response, 202, { ok: true })
      broadcast()
      return
    }

    if (method === 'POST' && url.pathname === '/api/receipts') {
      if (!producerAuthorized(request)) {
        sendJson(response, 401, { error: 'producer bearer token required' })
        return
      }
      const body = await readJson(request)
      if (!isRecord(body) || !safeStream(body.stream) || !validReceipt(body.receipt)) {
        throw Object.assign(new Error('stream and a valid receipt are required'), { status: 400 })
      }
      const added = addReceipt(body.stream, body.receipt)
      if (added === 'added') {
        const verdict = [body.receipt.effect, body.receipt.decision, body.receipt.outcome]
          .filter((value): value is string => typeof value === 'string' && value.length > 0)
          .join(' · ')
        addActivity(
          body.receipt.type,
          `${body.receipt.tool ?? body.stream}${verdict ? ` · ${verdict}` : ''}`,
        )
        broadcast()
      }
      sendJson(response, added === 'added' ? 202 : 200, {
        ok: true,
        duplicate: added === 'duplicate',
      })
      return
    }

    if (method === 'POST' && url.pathname === '/api/approvals') {
      if (!producerAuthorized(request)) {
        sendJson(response, 401, { error: 'producer bearer token required' })
        return
      }
      const body = await readJson(request)
      if (
        !isRecord(body) ||
        typeof body.id !== 'string' ||
        body.id.length === 0 ||
        body.id.length > 256 ||
        typeof body.user !== 'string' ||
        body.user.length > 512 ||
        typeof body.action !== 'string' ||
        body.action.length === 0 ||
        body.action.length > 512
      ) {
        throw Object.assign(new Error('invalid approval request'), { status: 400 })
      }
      if (pending.has(body.id) || settled.has(body.id)) {
        sendJson(response, 409, { error: 'approval id was already used' })
        return
      }
      const requestedWait =
        typeof body.timeoutMs === 'number' && Number.isFinite(body.timeoutMs) && body.timeoutMs > 0
          ? body.timeoutMs
          : MAX_APPROVAL_WAIT_MS
      const waitMs = Math.min(requestedWait, MAX_APPROVAL_WAIT_MS)
      const expiresAt = Date.now() + waitMs
      const timer = setTimeout(() => settleApproval(body.id as string, 'expired'), waitMs)
      timer.unref?.()
      pending.set(body.id, {
        id: body.id,
        user: body.user,
        action: body.action,
        ...(body.detail === undefined ? {} : { detail: body.detail }),
        expiresAt,
        response,
        timer,
      })
      response.on('close', () => {
        if (!response.writableEnded && pending.has(body.id as string)) {
          const approval = pending.get(body.id as string)
          if (approval) clearTimeout(approval.timer)
          pending.delete(body.id as string)
          settled.set(body.id as string, 'expired')
          addActivity('Approval connection closed', body.action as string)
          broadcast()
        }
      })
      addActivity('Approval requested', body.action)
      broadcast()
      // Deliberately keep the response open until the local UI settles or expires it.
      return
    }

    const decisionMatch = url.pathname.match(/^\/api\/approvals\/([^/]+)\/decision$/)
    if (method === 'POST' && decisionMatch) {
      if (!uiMutationAuthorized(request)) {
        sendJson(response, 403, {
          error: 'valid same-origin console session and CSRF token required',
        })
        return
      }
      const body = await readJson(request)
      const id = decodeURIComponent(decisionMatch[1] ?? '')
      if (!isRecord(body) || !['approved', 'denied'].includes(String(body.decision))) {
        throw Object.assign(new Error('decision must be approved or denied'), { status: 400 })
      }
      if (settled.has(id)) {
        sendJson(response, 409, { error: 'approval was already settled' })
        return
      }
      if (!pending.has(id)) {
        sendJson(response, 404, { error: 'pending approval not found' })
        return
      }
      settleApproval(id, body.decision as ApprovalDecision)
      sendJson(response, 200, { ok: true })
      return
    }

    if (method === 'POST' && url.pathname === '/api/policy') {
      if (!uiMutationAuthorized(request)) {
        sendJson(response, 403, {
          error: 'valid same-origin console session and CSRF token required',
        })
        return
      }
      await readJson(request)
      const report = latestReport()
      if (!report) {
        sendJson(response, 409, { error: 'publish or load an observation report first' })
        return
      }
      try {
        writeFileSync(policyOut, generateStarterPolicy(report), { encoding: 'utf8', flag: 'wx' })
      } catch (error) {
        const code = isRecord(error) ? error.code : undefined
        sendJson(response, code === 'EEXIST' ? 409 : 500, {
          error:
            code === 'EEXIST'
              ? `refusing to overwrite ${policyOut}`
              : `could not write policy: ${error instanceof Error ? error.message : String(error)}`,
        })
        return
      }
      addActivity('Starter policy written', policyOut)
      broadcast()
      sendJson(response, 201, { ok: true, path: policyOut })
      return
    }

    sendJson(response, 404, { error: 'not found' })
  }

  await new Promise<void>((resolveListen, reject) => {
    const onError = (error: Error) => reject(error)
    server.once('error', onError)
    server.listen(requestedPort, host, () => {
      server.off('error', onError)
      resolveListen()
    })
  })
  actualPort = (server.address() as AddressInfo).port
  const displayHost = host === '::1' ? '[::1]' : host
  const origin = `http://${displayHost}:${actualPort}`
  const bootstrapUrl = `${origin}/bootstrap?token=${encodeURIComponent(bootstrapToken)}`
  const keepalive = setInterval(() => {
    for (const response of eventStreams) {
      if (!response.writableEnded && !response.destroyed) response.write(': keepalive\n\n')
    }
  }, 20_000)
  keepalive.unref?.()

  let resolveClosed = () => {}
  const closed = new Promise<void>((resolvePromise) => {
    resolveClosed = resolvePromise
  })
  server.once('close', resolveClosed)

  const close = async () => {
    if (closing) return closed
    closing = true
    clearInterval(keepalive)
    for (const id of [...pending.keys()]) settleApproval(id, 'expired')
    for (const response of eventStreams) response.end()
    eventStreams.clear()
    await new Promise<void>((resolveClose, reject) => {
      server.close((error) => (error ? reject(error) : resolveClose()))
      server.closeIdleConnections?.()
    })
  }

  if (options.open !== false) openBrowser(bootstrapUrl)
  return { origin, bootstrapUrl, token: producerToken, closed, close }
}

/** CLI lifecycle wrapper: load optional files, print bridge config, and stop on SIGINT/SIGTERM. */
export async function runConsole(options: RunConsoleOptions = {}): Promise<{ code: number }> {
  let initialReport: unknown
  let initialReceipts: Receipt[] | undefined
  try {
    if (options.reportFile) initialReport = JSON.parse(readFileSync(options.reportFile, 'utf8'))
    if (options.receiptsFile) {
      const parsed: unknown = JSON.parse(readFileSync(options.receiptsFile, 'utf8'))
      if (!Array.isArray(parsed)) throw new Error('receipt file must contain a JSON array')
      initialReceipts = parsed as Receipt[]
    }
  } catch (error) {
    console.log(`✗ could not load console input: ${(error as Error).message}`)
    return { code: 1 }
  }

  let handle: ConsoleServerHandle
  try {
    handle = await startConsole({
      port: options.port,
      open: options.open,
      policyOut: options.policyOut,
      initialReport,
      initialReceipts,
    })
  } catch (error) {
    console.log(`✗ could not start nominee console: ${(error as Error).message}`)
    return { code: 1 }
  }

  console.log(`nominee console listening on ${handle.origin}`)
  console.log(`Open: ${handle.bootstrapUrl}`)
  console.log(`export NOMINEE_CONSOLE_URL=${handle.origin}`)
  console.log(`export NOMINEE_CONSOLE_TOKEN=${handle.token}`)
  console.log('Press Ctrl+C to stop.')

  const stop = () => void handle.close()
  process.once('SIGINT', stop)
  process.once('SIGTERM', stop)
  try {
    await handle.closed
  } finally {
    process.off('SIGINT', stop)
    process.off('SIGTERM', stop)
  }
  return { code: 0 }
}
